package com.nats.exception;

/**
 * Customized Exception Handling
 *
 * @author vaibhav-scaletech
 */
public class CustomException extends RuntimeException {

    /**
     * @param message, Only throw a custom exception using the message generated by the default exceptions.
     */
    public CustomException(String message) {
        super(message);
    }

    /**
     * @param cause, Only throw a custom exception using the cause of default exceptions.
     */
    public CustomException(Throwable cause) {
        super(cause);
    }
}
